function createUcrt(criterionName)
%   Create template MATLAB routine for user-defined failure criterion.
%
%   ABD.CREATEUCRT(<criterion-name>) creates a template MATLAB
%   routine file with the name <criterion-name>.m. The required inputs and
%   outputs are supplied in the function header.
%
%   To use the routine for a strength calcuation with Layup Analysis Tool,
%   specify the following in the layup definition file:
%
%     OUTPUT_STRENGTH = {@<criterion-name>, '<param>'};
%
%   Layup Analysis Tool 5.1.0 Copyright Louis Vallance 2026
%   Last modified 12-Feb-2026 12:33:07 UTC
%

%% - DO NOT EDIT BELOW LINE
%_______________________________________________________________________
%%
% Get the date string
dateString = char(datetime('now'));
dateStringFile = dateString;

% Get the user's machine name
[~, hostname] = system('hostname');

% Open the template file
fid = fopen([criterionName, '.m'], 'w');

% Print the contents
fprintf(fid, ...
    ['function [UCRT] = %s(INFO, UCRT, MATERIAL_MECH, MATERIAL_FAIL, TENSORS)\n' ...
    '%%%s    Routine for user-defined failure criterion.\n',...
    '%%    To use this routine for a strength calculation with Layup Analysis\n%%    Tool, specify the following in the layup definition file:\n',...
    '%%      OUTPUT_STRENGTH = {@%s, {''RESERVE'' | ''VALUE''}};\n%%\n',...
    '%%    Routine interface\n',...
    '%%      [UCRT] = %s(INFO, UCRT, MATERIAL_MECH, MATERIAL_FAIL, TENSORS)\n',...
    '%%\n',...
    '%%    Variables to be provided to the routine\n',...
    '%%      INFO [struct], Layup information\n',...
    '%%        PLY_COUNT: Number of plies (layup)\n',...
    '%%        SECTION_POINTS: Number of section points (per ply)\n',...
    '%%        TOTAL_POINTS: Total number of sample points (layup)\n',...
    '%%        FAILURE_PARAMETER: 1 (strength reserve factor); 2 (criterion value)\n',...
    '%%      UCRT [1xTOTAL_POINTS double], Pre-initialised buffer for failure criterion values\n',...
    '%%      MATERIAL_MECH [struct], Mechanical material properties\n',...
    '%%      MATERIAL_FAIL [struct], Composite strength properties\n',...
    '%%        STRESS: Stress-based failure criteria\n',...
    '%%        STRAIN: Strain-based failure criteria\n',...
    '%%        HASHIN: Hashin damage initiation criteria\n',...
    '%%        LARC05: LaRC05 damage initiation criteria\n',...
    '%%      TENSORS [struct], Stress/strain tensor data\n',...
    '%%        E_MIDSPAN [PLY_COUNTx1 double], Midspan strains\n',...
    '%%        E_PLY_XY [3xTOTAL_POINTS double], Ply strain in global (X-Y) coordinates\n',...
    '%%        S_PLY_XY [3xTOTAL_POINTS double], Ply stress in global (X-Y) coordinates\n',...
    '%%        E_PLY_ALIGNED [3xTOTAL_POINTS double], Ply strain in ply (1-2) coordinates\n',...
    '%%        S_PLY_ALIGNED [3xTOTAL_POINTS double], Ply stress in ply (1-2) coordinates\n',...
    '%%        E_THERM_XY [3xTOTAL_POINTS double], Stress-free ply strains due to thermal process in global (X-Y) coordinates\n',...
    '%%        E_HYDRO_XY [3xTOTAL_POINTS double], Stress-free ply strains due to moisture process in global (X-Y) coordinates\n',...
    '%%        E_THERM_ALIGNED [3xTOTAL_POINTS double], Stress-free ply strains due to thermal process in ply (1-2) coordinates\n',...
    '%%        E_HYDRO_ALIGNED [3xTOTAL_POINTS double], Stress-free ply strains due to moisture process in ply (1-2) coordinates\n',...
    '%%\n',...
    ['%%    NOTE: For a description of the mechanical material/composite strength\n%%    property identifieres, run the command >> help abd.main\n%%    and consult the sections "U',...
    'SE CASE I" and "USE CASE III",\n%%    respectively.\n'],...
    '%%\n',...
    ['%%    NOTE: The tensor variables are arranged as follows\n%%    (1, :) -> 11-component of stress/strain\n%%    (2, :) -> 22-component of stress/strain\n%%    (3, :) -> 12-c',...
    'omponent of stress/strain\n'],...
    '%%\n',...
    ['%%    NOTE: The value of FAILURE_PARAMETER is the requested failure\n%%    parameter. It is used for information purposes in case the author\n%%    wishes to provide strengt',...
    'h reserve and criterion value output.\n%%\n'],...
    '%%    Variables returned from the routine\n',...
    '%%      UCRT [1xTOTAL_POINTS double], Computed failure criterion values\n',...
    '%%\n',...
    '%%    FILE AUTO GNERATED BY %s ON %s.\n%%\n',...
    '%%    Insert code below:\n\n',...
    '%%__________________________________________________________________________\n',...
    '%%%%    END OF FILE\n',...
    'end\n'], criterionName, upper(criterionName), criterionName, criterionName, hostname(1.0:end - 1.0), dateStringFile);

% Close the template file
fclose(fid);

% Open the template file for editing
edit(criterionName)
end